config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'experiences#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :experiences do
    resources :bookings, only: [:new, :create, :destroy]
  end
  resources :bookings, only: [:index]
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Experience Lisbon</h1>
    <p><span id="typed-text"></span></p>
    <%=link_to "Discover", "#experiences", :class => "button-banner" %>
  </div>
</div>

app/views/shared/_card.html.erb
<% if experience.id != nil %>
<div class="card ">
  <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0)), url(<%=experience.photo%>);">
    <span class="card-category"><%=experience.category%></span>
    <div class="card-description">
      <h2><%=experience.title.upcase%></h2>
    </div>
    <% if experience.user.photo.url == nil %>
    <i class="far fa-user card-user avatar-border-white-i"></i>
    <% else %>
    <%= image_tag experience.user.photo.url(:thumnail), :class => "far fa-user card-user avatar-small avatar-border-white"%>
    <% end %>
    <%=link_to experience_path(experience) do %>
    <div class="card-footer">
      <p><i class="fas fa-map-marker"></i><%=experience.address%> (<%=experience.price.to_i%>€)</p>
      <div class="card-time">
        <p>[<%=experience.duration%>h]</p>
      </div>
    </div>
    <%end%>
  </div>
</div>
<%end%>

app/views/shared/_message_booking.html.erb
<div class="message" data-booking-id="<%= booking.id %>">
  <%  if User.find(@experiences.find(booking.experience_id).user_id).photo.url != nil %>
  <%= image_tag User.find(@experiences.find(booking.experience_id).user_id).photo.url(:thumnail), :class => "avatar avatar-border-turqoise" %>
  <% else %>
  <i class="far fa-user avatar-border-turqoise-i" style="font-size: 24px"></i>
  <% end %>
  <div class="message-name">
    <h3> Hosted from: <%= (User.find(@experiences.find(booking.experience_id).user_id)).first_name%></h3>
    <p> <%=booking.date_time.strftime("%b %e, %l:%M %p")%></p>
  </div>
  <div class="message-body">
    <p><strong><%=@experiences.find(booking.experience_id).title%></strong></p>
    <p>
      <%=booking.message%>
    </p>
  </div>
  <%if booking.status == nil || "accepted"%>
  <div class="message-status">
    <p class="status accepted">Booked</p>
  <%end%>
    <p class="message-price"><%=@experiences.find(booking.experience_id).price.to_i%>€</p>
    <%= link_to experience_booking_path(@experiences.find(booking.experience_id), booking), method: :delete,remote: true, :class => "message-link" do %>
    <i class="far fa-trash-alt"></i>
    <%end%>
  </div>
</div>

app/views/shared/_message_hosting.html.erb
<div class="message" data-booking-id="<%= booking.id %>">
  <%  if User.find(booking.user_id).photo.url != nil %>
  <%= image_tag User.find(booking.user_id).photo.url(:thumnail), :class => "avatar avatar-border-turqoise" %>
  <% else %>
  <i class="far fa-user avatar-border-turqoise-i" style="font-size: 24px"></i>
  <% end %>
  <div class="message-name">
    <h3> Booked by: <%= User.find(booking.user_id).first_name%></h3>
    <p> <%=booking.date_time.strftime("%b %e, %l:%M %p")%></p>
  </div>
  <div class="message-body">
    <p><strong><%=@experiences.find(booking.experience_id).title%></strong></p>
    <p>
      <%=booking.message%>
    </p>
  </div>
  <div class="message-status">
    <p class="status accepted">Booked</p>
    <p class="message-price"><%=@experiences.find(booking.experience_id).price.to_i%>€</p>
    <%= link_to experience_booking_path(@experiences.find(booking.experience_id), booking), method: :delete,remote: true, :class => "message-link" do %>
    <i class="far fa-trash-alt"></i>
    <%end%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
<% if user_signed_in? %>
  <%= render partial: '/shared/navbar_02' %>
<% else %>
  <%= render partial: '/shared/navbar_01' %>
<% end %>
</div>

app/views/shared/_navbar_01.html.erb
<div class="navbar-xp">
  <!-- Logo -->
  <a href="/" class="navbar-xp-brand">
   <%= image_tag('favicon.png') %>
 </a>

 <!-- Right Navigation -->
 <div class="navbar-xp-right hidden-xs hidden-sm">
  <div class="search-container">
  <%= form_tag "#{experiences_path}/#experiences", method: :get do %>
<div class="search-components">
  <%= label_tag :search do %>
  <i class="fas fa-search"></i>
<% end %>
  <%= text_field_tag :search,
    params[:search],
    class: "search-form",
    placeholder: "Search activities" %>
<% end %>
</div>
</div>

<%= link_to 'Sign Up', new_user_registration_path, :class => "navbar-xp-item navbar-xp-link-01" %>
<%= link_to 'Log In', new_user_session_path, :class => "navbar-xp-item navbar-xp-link" %>
</div>

<!-- Dropdown appearing on mobile only -->
<div class="navbar-xp-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-xp-dropdown-menu">
      <li><%= link_to 'Sign Up', new_user_registration_path, :class => "navbar-xp-item navbar-xp-link-01" %></li>
      <li><%= link_to 'Log In', new_user_session_path, :class => "navbar-xp-item navbar-xp-link" %></li>
    </ul>
  </div>
</div>
</div>

app/views/shared/_navbar_02.html.erb
<div class="navbar-xp">
  <!-- Logo -->
  <a href="/" class="navbar-xp-brand">
    <%= image_tag('favicon.png') %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-xp-right hidden-xs hidden-sm">
     <div class="search-container">
  <%= form_tag "#{experiences_path}/#experiences", method: :get do %>
<div class="search-components">
  <%= label_tag :search do %>
  <i class="fas fa-search"></i>
<% end %>
  <%= text_field_tag :search,
    params[:search],
    class: "search-form",
    placeholder: "Search for an activity"%>
<% end %>
</div>
</div>
      <p  class="navbar-xp-item navbar-xp-link-welcome">Welcome</p>
      <% if current_user.first_name == nil %>
      <p class="navbar-xp-item navbar-xp-link-name"><%= current_user.email %></p>
      <% else %>
      <p class="navbar-xp-item navbar-xp-link-name"><%= current_user.first_name %></p>
      <% end %>

      <!-- Profile picture with dropdown list -->
      <div class="navbar-xp-item">
        <div class="dropdown">
          <% if User.instance_methods.include? :photo %>
          <% if current_user.photo.url == nil %>
          <i class="far fa-user dropdown-toggle avatar-border-turqoise-i " id="navbar-xp-menu" data-toggle="dropdown"></i>
          <% else %>
          <%= image_tag current_user.photo.url(:thumnail), :class => "avatar dropdown-toggle avatar-border-turqois", :id => "navbar-xp-menu",data: { toggle: 'dropdown' }%>
          <%end%>
          <%else%>
          <i class="far fa-user dropdown-toggle avatar-border-turqoise-i " id="navbar-xp-menu" data-toggle="dropdown"></i>
          <%end%>

        <ul class="dropdown-menu dropdown-menu-right navbar-xp-dropdown-menu">
          <li><%=link_to "My bookings", bookings_path %></li>
          <li><%=link_to "Create Experience", new_experience_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <!-- <li><a href="#">Dashboard</a></li> -->
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-xp-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-xp-dropdown-menu">
          <li><p>Welcome</p></li>
          <li>  <% if current_user.first_name == nil %>
            <p class="navbar-xp-item navbar-xp-link-name"><%= current_user.email %></p>
            <% else %>
            <p class="navbar-xp-item navbar-xp-link-name"><%= current_user.first_name %></p>
            <% end %></li>
          </ul>
        </div>
      </div>
</div>